# Generated by Django 5.1.4 on 2025-02-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('suggestion', models.CharField(max_length=50)),
            ],
        ),
    ]
