# Generated by Django 5.1.4 on 2025-02-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='suggestion',
            field=models.TextField(max_length=50),
        ),
    ]
