# Generated by Django 5.1.4 on 2025-02-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_alter_feedback_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
